name: 🚀 Deploy to Hodi Host

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p 22974 alouda.maurice.webcup.hodi.host >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -P 22974 -r * alouda@alouda.maurice.webcup.hodi.host:/home/alouda/public_html/
